### ISSUE TITLE
Model fit never finishes

### ISSUE THREAD

**Issue by andreysharapov** [meelgroup/MLIC#1]
Hello

I am trying to use the package but I can't make the code listed in the front page run till the end, except for some data sets. The runtime numbers reported in the paper just don't seem to materialize for me.  

Let say I do

import rulelearning
model = rulelearning.imli(numClause=5)
X,y=model.discretize("/Users/sharapov/Documents/MLIC/benchmarks/adult_data_bintarget.csv")
model.fit(X,y)

This does not seem to finish.

I would appreciate if you could give me some tips on how to run the code and use it for practical purposes, so that it finishes within a reasonable amount of time. 

Thank you

**Comment by bishwamittra** [comment]
Hi Andrey, 

Here are some tips on how to run the code faster.  

1. You can set a higher value of numPartiton = 32, 64, ..., 256 for speed up. Here numPartition refers to the number of batches in which the training data is split.  Unless specified, the algorithm decides the default value of numPartition based on the size of the training data. 

2. In our paper, we report numClause=1, 2, 3. If you set numClause = 5, the algorithm takes a longer time, which is often not practical. We are now working on how to get a speedup even when numClause is higher. 

3. You can also set a lower value of numThreshold = 3, 4 in the method discretize().  A lower value of numThreshold generates fewer binary features in the discretized dataset.  By default, the algorithm splits a real-valued feature to 10 intervals/categories. 
``
X,y=model.discretize("benchmarks/iris_bintarget.csv", numThreshold = 4)
`` 

4. In our experiments, we use Open-wbo as the MaxSAT solver as we find it faster than other solvers. 

Regards,
Bishwa

**Comment by andreysharapov** [comment]
Hi Bishwa

Thank you for getting back to me so quickly. I will try the tweaks you suggested. I have another question to you. Since you use MaxSAT solver, have you thought about using one implemented on a quantum annealer like D-Wave. There was some work done in this direction https://arxiv.org/abs/1811.02524.

I just wonder if this could speed up calculations quite significantly. Could also be a nice application of quantum computing.

Best wishes
