### ISSUE TITLE
Prediction through MaxSAT formulation

### ISSUE THREAD

**Issue by thiagoalvesifce** [meelgroup/MLIC#2]
Hello, thanks for sharing the code.

Could you please explain why you use a MaxSAT solver for prediction? 
Isn't this way slower than through a direct application of the learned rules?

Best regards!

**Comment by bishwamittra** [comment]
Thanks for your interest. 

You are correct. MaxSAT formulation is slow particularly for the task of prediction. Therefore, we have incorporated a mini-batch learning scheme that solves a series of smaller MaxSAT instances to compute the rule. Our mini-batch learning is significantly faster than learning on the whole training set.

If you have any queries, please drop a mail at bgohsh@u.nus.edu. 

Best regards, 
Bishwa
