### ISSUE TITLE
How to apply the model on new data?

### ISSUE THREAD

**Issue by JATC1024** [meelgroup/MLIC#3]
As the title suggests, how do I apply the model on unseen data since I don't have the label for those samples (of course) while the method "predict" requires the labels?

**Comment by bishwamittra** [comment]
I have made a new release that does not require labels in the prediction function. Please try it.

**Comment by JATC1024** [comment]
Could you check it again? The method returns an empty list instead of the predictions.
![image](https://user-images.githubusercontent.com/22787132/103602876-b3064a80-4f3f-11eb-8602-98ccb159506f.png)

**Comment by bishwamittra** [comment]
It is working perfectly in my pc. Can you share your code and dataset?

**Comment by JATC1024** [comment]
Hi, the zip file below contains 3 files, train.npa, test.npa and labels.npa. You can use numpy.load to load them into numpy arrays, i.e. `train = numpy.load(train.npa)`. The file train.npa contains a numpy array of size (22036, 200), the test file contains a numpy array of size (113077, 200) and the labels file contain a numpy array of size (22036,). I create and fit a model by using
`clf = imli(rule_type="CNF", num_clause=3, data_fidelity=1, solver="open-wbo", work_dir="tmp_dir", verbose=True)`
`clf.fit(train, labels)`
and then predict by
`y_pred = clf.predict(test)`
[data.zip](https://github.com/meelgroup/MLIC/files/5769012/data.zip)

**Comment by bishwamittra** [comment]
I have resolved a bug in the prediction function that could not output labels for large train or test set. Now it should work. Please try the new release.

**Comment by bishwamittra** [comment]
<img width="615" alt="Screenshot 2021-01-05 at 10 00 43 PM" src="https://user-images.githubusercontent.com/5962720/103668719-9b5fae00-4fa1-11eb-9b4c-a2c15650c606.png">

This is the output I have got. Have you installed all dependencies? Could you print the rule after the training is done? Also try to see if you could run the python notebook  in your pc. 

https://github.com/meelgroup/MLIC/blob/master/documentation.ipynb

**Comment by JATC1024** [comment]
It appears that the model works when the number of clauses is 3 but not when it is 10 (which is in my case). This is the rule I have got when num_clause=10
![image](https://user-images.githubusercontent.com/22787132/103725788-eb725b00-5009-11eb-863c-eb0c130472f9.png)

Another thing you could consider is that, after executing `clf.predict()`, the rule becomes this
![image](https://user-images.githubusercontent.com/22787132/103725905-312f2380-500a-11eb-92f9-82618bd6b991.png)

**Comment by bishwamittra** [comment]
Can you try to install the following library and test on your dataset. 

pip install -i https://test.pypi.org/simple/ pyrulelearn==1.0.8

**Comment by JATC1024** [comment]
It works now, thanks
